from numpy import linalg as Alimushkin
import numpy as kirill
print('Пример ввода Данных \n ''a b c \n d e f \n r v o')# визуальный кайф
print('Введите a')
a= int(input())
print('Введите b')
b= int(input())
print('Введите c')
c= int(input())
print('Введите d')
d= int(input())
print('Введите e')
e= int(input())
print('Введите f')
f= int(input())
print('Введите r')
r= int(input())
print('Введите v')
v= int(input())
print('Введите o')
o= int(input())
arr1 = kirill.array([[a, b, c], [d, e, f],[r,v,o]])
print(" Первая Матрица\n", arr1)
print("Ранг Матрицы\n", Alimushkin.matrix_rank(arr1, 1))