import numpy as kirill
print('Пример ввода Данных \nПервая Матрица    Вторая Матрица \n ''a b c             p q s\n d e f             v w m\n r v o             x l z')# визуальный кайф
print('Введите a')
a= int(input())
print('Введите b')
b= int(input())
print('Введите c')
c= int(input())
print('Введите d')
d= int(input())
print('Введите e')
e= int(input())
print('Введите f')
f= int(input())
print('Введите r')
r= int(input())
print('Введите v')
n= int(input())
print('Введите o')
o= int(input())
print('Введите p')
p= int(input())
print('Введите q')
q= int(input())
print('Введите s')
s= int(input())
print('Введите v')
v= int(input())
print('Введите w')
w= int(input())
print('Введите m')
m= int(input())
print('Введите x')
x= int(input())
print('Введите l')
l= int(input())
print('Введите z')
z= int(input())


arr3 = kirill.array([[a, b,c], [d, e,f],[r,n,o]])
print("Первая Матрица")
print(arr3)
print("Размер Первой Матрицы", arr3.shape)

arr4 = kirill.array([[p, q,s], [v, w,m],[x,l,z]])
print("Вторая матрица ")
print(arr4)
print("Размер Второй Матрицы", arr4.shape)

mama2top = kirill.matmul(arr3, arr4)
print("Результат Произведения Матриц ")
print(mama2top)
print("Размер Произведения Матриц", mama2top.shape)